create table if not exists orders(
  id varchar(100) not null,
  finished boolean default false,
  scanned_at bigint default 0,
  status_log varchar(100) default "created",
  seller_id varchar(20) not null,
  buyer_pubkeyhash varchar(100) not null,
  seller_pubkeyhash varchar(100) not null,  
  buyer_address varchar(200) not null,
  seller_address varchar(200) not null,  
  ada_price decimal(10, 2) not null,
  contract_address varchar(100) not null,
  contract_params text not null,
  contract_state int default null,
  contract_price int unsigned not null,
  contract_collateral int unsigned not null,
  contract_units int unsigned not null,
  product_id varchar(20) not null,
  product_name varchar(200) not null,
  product_price int unsigned not null,
  product_collateral int unsigned not null,  
  product_sku varchar(100) not null,
  product_model varchar(200) not null,
  product_brand varchar(200) not null,
  product_features mediumtext not null,
  product_bullet_list text not null,
  product_discount boolean not null,
  product_discount_value int unsigned not null,
  watch_until bigint not null,
  pending_until bigint not null,
  pending_tx varchar(200) default null,
  pending_block varchar(200) default null,
  return_tx varchar(200) default null,
  return_block varchar(200) default null,
  locking_tx varchar(200) default null,
  locking_block varchar(200) default null,
  updated_at timestamp default current_timestamp,
  created_at timestamp default current_timestamp,
  schema_v int unsigned default 0,
  primary key(id),
  index idx_finished (finished),
  index idx_created_at (created_at),
  index idx_scanned_at (scanned_at)
) ENGINE=InnoDB;
